name: Linter

on:
  push:
    branches:
      - '**'

jobs:
  cpu:
    name: "CPU tests"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pyink==23.10.0 pytype==2024.2.27
    # - name: Typecheck the code with pytype
    #   run: |
    #     pytype --jobs auto --disable import-error src/maxdiffusion/
    - name: Analysing the code with pylint in maxdiffusion/
      run: |
         pylint --fail-under=7 src/maxdiffusion/  && \
         echo 'maxdiffusion PyLint check successful' || { echo \
         'PyLint check has failed. Please run bash code_style.sh to fix issues'; exit 20; }
    - name: Analysing the code with pylint in end_to_end/
      run: |
         pylint --fail-under=7 end_to_end/ && \
         echo 'PyLint check on pend_to_end/ is successful' || { echo \
         'PyLint check has failed. Please run bash code_style.sh to fix issues'; exit 20; }
    - name: Analysing the code with pyink in maxdiffusion/
      run: |
        pyink src/maxdiffusion --check --diff --color --pyink-indentation=2 --line-length=125
    - name: Analysing the code with pyink in end_to_end/
      run: |
        pyink end_to_end --check --diff --color --pyink-indentation=2 --line-length=125


